### ISSUE TITLE
MaSh 2.0 Version

### ISSUE THREAD

**Issue by ProtectorGamer** [BOSS294/PROJECT-991#15]
I've tried to re-code the MaSH 2.0 with 70% self-coding and 30% Chat GPT Support.

Most of the functions, callbacks and Voice Generaters has been updated with upto system

File has been attached below
[MaSh2.0.zip](https://github.com/user-attachments/files/16568674/MaSh2.0.zip)

**Comment by BOSS294** [comment]
Thanks for the contribution @ProtectorGamer, We will look into it
