### ISSUE TITLE
Task 001 ( Change the description of main  remove chat-gpt completely and add what we are creating.

### ISSUE THREAD

**Issue by nileshkumars961** [BOSS294/PROJECT-991#6]
### Discussed in https://github.com/BOSS294/PROJECT-991/discussions/4

<div type='discussions-op-text'>

<sup>Originally posted by **BOSS294** May 25, 2023</sup>
Task assigned to @nileshkumars961 to use chat-gpt 3 and generate a new description for our main readme.MD.

You have to update the readme.md file which must include this 

`Our features
Our roadmap
Our AI's Name
`
Please reply to this discussion once you have started and completed the task.

Incase any doubt arises you can create a discussion here only.

"WHAT IS THE WORD LIMIT FOR DESCRIPTION?"
</div>

**Comment by BOSS294** [comment]
CLOSED 🔒
